### ISSUE TITLE
大佬能不能添加一个保供商品自动选择，过滤掉蔬菜组合，或者输入关键字，判断关键字出现，即抢购

### ISSUE THREAD

**Issue by Mason-star** [sari3l/sams_helper#17]

**Comment by sari3l** [comment]
关键字在标题的话，基本上就是“蔬菜组合”&“保供套餐X”两种，排除会好一些，等下我加一下
（不过感觉越来越臃肿，效率并没有提上去🤯）

**Comment by sari3l** [comment]
可拉最新 commit，在config.yaml中进行配置

```yaml
# 保供抢购排除关键字
supplyExcludeSet:
  # 是否开启
  isEnabled: true
  # 排除含有以下关键字的内容，例：["蔬菜", "保供套餐C"]
  keyWords: ["蔬菜"]
```
