### ISSUE TITLE
是不是改策略了

### ISSUE THREAD

**Issue by meviyysss** [sari3l/sams_helper#38]
![Uploading 截屏2022-04-28 下午2.58.50.png…]()

看下~~~~

**Comment by meviyysss** [comment]
<img width="1546" alt="截屏2022-04-28 下午2 58 50" src="https://user-images.githubusercontent.com/103988517/165695271-d7e5adca-1e83-49e0-a072-1bdc1a6d7acd.png">

**Comment by sari3l** [comment]
目前已知访问太多可能会被 BAN，山姆调整策略了

**Comment by meviyysss** [comment]
是啊 调外地也无法下单  同样警告 还有救吗~

**Comment by sari3l** [comment]
> 是啊 调外地也无法下单 同样警告 还有救吗~

等待半小时后应该会解封，同时支持自定义代理，如果有自己的代理或者代理池应该也可以绕过

**Comment by meviyysss** [comment]
什么意思呀 怎么操作~ vpn吗

**Comment by meviyysss** [comment]
如果是使用旧版频率偏高，可以使用新版默认 1 秒，且可以从config.yaml - sleepTimeSet自定义时间避免过于频繁导致拦截

我看了下 现在都是1000

**Comment by sari3l** [comment]
> 如果是使用旧版频率偏高，可以使用新版默认 1 秒，且可以从config.yaml - sleepTimeSet自定义时间避免过于频繁导致拦截
> 
> 我看了下 现在都是1000

那新策略应该是单 IP 访问次数做限制了

**Comment by sari3l** [comment]
这种情况如果有代理可以试下能不能绕过，因为目前不知道什么原因我还没有遇到过拦截

```yaml
# 代理设置
proxySet:
  # 是否开启代理
  isEnabled: false
  # 代理 URL
  proxyUrl: "http://127.0.0.1:8080"
```
