### ISSUE TITLE
updateStoreForce下，能否每次重新print商店信息

### ISSUE THREAD

**Issue by futuration** [sari3l/sams_helper#63]
若代码简单，是否能点拨一下我自己改就好了。重新print商店信息能让我感到放心一点hhhh。无有效商品后print获取购物车总会让我有种updateStoreForce是否没开的不安。

**Comment by futuration** [comment]
另外我发现大佬您检查了isSelected这个参数。这是为了以后做手动选择购物车吗？现在似乎是自动全选购物车下单？

**Comment by sari3l** [comment]
自动输入已在config.yaml中标明
```yaml
# 自动输入设置
autoInputSet:
  # 是否开启
  isEnabled: false
  # 支付方式序号
  # 0->微信 | 1->支付宝 | 2->银联 | 3->沃尔玛礼品卡
  inputPayMethod: 0
  # 地址序号
  inputAddress: 0
  # 优惠券序号列表，例：[0,1,2]
  inputCouponList: []
```

现代码是如有商店有变动才会显示，如需每次获取都显示，修改main.go 193
```go
var isChange = false
```
为
```go
var isChange = true
```
