### ISSUE TITLE
如何添加商品加入购物车，商品是无货状态

### ISSUE THREAD

**Issue by Manchuker1120** [sari3l/sams_helper#70]
如何添加商品加入购物车，商品是无货状态

**Comment by sari3l** [comment]
程序同级目录保存`goodsList.yaml`文件，里面每行填写`完整商品名: 数量`

同时篇日志`config.yaml`以下内容

```yaml
# （精准）自动搜索、强制添加指定商品
# 注：通过此功能无货商品可提前加入购物车
addGoodsFromFileSet:
  # 是否开启
  isEnabled: true
  # 加载方式，冷加载只执行一次，热加载每隔 stepGoodsHotModeSleep 循环执行
  # 1->冷加载 | 2->热加载
  mode: 1
  # 显示商品细节
  showGoodsInfo: true
```
