### ISSUE TITLE
运行的时候对config文件显示no such file or directory

### ISSUE THREAD

**Issue by crashXG** [sari3l/sams_helper#78]

**Comment by sari3l** [comment]
cd 到目录下执行程序

**Comment by crashXG** [comment]
sorry, 能给一个具体的指令嘛？小白，对程序懵逼。。已经google了很久，也尝试了一些，但还是没成功。。

**Comment by sari3l** [comment]
> sorry, 能给一个具体的指令嘛？小白，对程序懵逼。。已经google了很久，也尝试了一些，但还是没成功。。

请直接下载v1.2.2 已经允许跨目录执行了

**Comment by crashXG** [comment]
太感谢了！！

**Comment by sari3l** [comment]
```yaml
# 保供抢购关键字黑白名单筛选
supplySet:
  # 只关注保供套餐
  onlySupply: true
```
